### ISSUE TITLE
Build a Single Post Page

### ISSUE THREAD

**Issue by congtoanle** [vitorfs/bootcamp#103]
Anybody can build a single post page from a user like https://www.facebook.com/manchesterunited/posts/10155038617982746

**Comment by sebastian-code** [comment]
Hi @congtoanle I haven't been able to understand your issue, can you elaborate on that?

**Comment by congtoanle** [comment]
yeah, Now we have a Feed with multi Posts, How can I have a page with just a SINGLE POSTS

**Comment by sebastian-code** [comment]
If you're talking about looking to just a single post, just click on the post title.

**Comment by sebastian-code** [comment]
Hey @congtoanle how this ended working for you? Do you still need help?

**Comment by congtoanle** [comment]
@sebastian-code  I mean Single Post, no Single Author Feed. It is a page with ONE FEED. Sorry if i said a mistake.

**Comment by sebastian-code** [comment]
I'm sorry @congtoanle I haven't been able to understand to you. If you are talking about a page per individual post, as I said, you can achieve that selecting the article's title in the articles page. If by any means what you're talking about is a single page with infinite scroll, then no, there is no way to achieve that at this moment, because Bootcamp doesn't has that possibility.

If that last part is what you want, you can try to develop it and you can suggest it to be included here as a PR.

**Comment by congtoanle** [comment]
Thank you for your support Sebastian
