### ISSUE TITLE
Add AJAX Autocomplete Search

### ISSUE THREAD

**Issue by SurajKamble** [vitorfs/bootcamp#107]
The search box doesn't show suggestions for auto-completing. It can be implemented using JQuery.

**Comment by sebastian-code** [comment]
Hi @SurajKamble. It sounds interesting, but I still don't see why or how it will be useful for the software, can you elaborate around this use case and the purpose of this feature and its positive impacts for the user base?

**Comment by SurajKamble** [comment]
When a person is searching for a user, question or article the search bar will suggest a few search "terms" based on data in the database, similar to google search engine. This way, instead of the user typing the whole search query, they will be provided a few suggestions to select from. Let's say the user is searching for something and they type "python" in the search bar, they will be suggested a few options (could be usernames or articles or questions that contain the word "python") to select from.

**Comment by sebastian-code** [comment]
To be honest @SurajKamble I still don't see it as feature needed by the user base, but (and this is a really big but) I have by any means a real perception of actual use cases of Bootcamp in the wild. This kind of features fall really far from the original scope, but a lot of time has pass since the beginning, so perhaps there is an actual opportunity for this, where the users can benefit from it.

If you want, please go ahead and provide the proper PR for this. And don't forget to include the respective test for the code :wink:, is always nice to keep that in good shape.

**Comment by SurajKamble** [comment]
When you search something on Facebook, you're given a few suggestions in a drop-down, similarly, we can implement it for our site. I have added the feature to my local repo, I will add test cases and provide the PR.

**Comment by sebastian-code** [comment]
Great @SurajKamble, I appreciate it. I forgot to clarify this, please submit the PR against the develop branch.

**Comment by sebastian-code** [comment]
Solved with #110. Closing now.
