### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by akankshagr** [vitorfs/bootcamp#124]

**Comment by sebastian-code** [comment]
Hi @akankshagr Can you provide additional information on this? At this development stage the code is fully functional and the login workflow is working without issue.

If you have the error stacktrace, and if you can elaborate on the issue you are having and the necessary steps to reproduce the error, I can help you in a better way.

**Comment by akankshagr** [comment]
Now its working fine can you tell me how can I add forgot my password and social login(facebook,google) functionality

**Comment by sebastian-code** [comment]
I'm glad is working, and about your request, to be honest, it will require some work from your side because that was outside the scope of the initial project; you'll need to develop the code with the required functionalities and the proper workflow. As a basic approach I would recommend to incorporate some kind of social user management.

Django has some interesting packages for that, but it will require than you revamp completely the user and authentication workflow, and also the profile structure.
