### ISSUE TITLE
Creating Universally Unique ID

### ISSUE THREAD

**Issue by feedgit** [vitorfs/bootcamp#126]
I get problem because I want to auto generate Unique ID for every model field. Example: User 1 have ID 1, User 2 have ID 2, Feed 1 have ID 3. Feed 2 have ID 4, ... like Facebook design. (fb.com/4 -> Mark Profile, fb.com/10104096471894281 -> Mark Feed)
How can I do this like Facebook? Thank you Vitorfs!

**Comment by congtoanle** [comment]
I found a solution: Sharding PostgreSQL and generate by timestamp, ShardID. How do you think?

**Comment by sebastian-code** [comment]
Hi @feedgit This is a really complex situation, far beyond the original project intent. I'm glad than you have this kind of interest. About your need, and your solution, I still don't understand the full scope of what you want to achieve, because this part confuses me:
> I want to auto generate Unique ID for every model field. Example: User 1 have ID 1, User 2 have ID 2, Feed 1 have ID 3. Feed 2 have ID 4, ... like Facebook design. (fb.com/4 -> Mark Profile, fb.com/10104096471894281 -> Mark Feed)
You say you want to create a unique ID for every single field for every model (I don't see want you want to do something than complex, mainly because I haven't been able to imagine the use case), but the example you provide indicate than what you really want is to create a unique ID for every instance.

About PostgreSQL sharding, I think that is used for other use cases, but I'm not familiar with the process and implementation, so sorry, I can't be of help there. And about your question, if what you want is the first use case, I have no valid suggestion to make to you, but if what you want to implement is the second one, have you considered using UUID?

I hope it helps.

**Comment by feedgit** [comment]
@Sebastian Code. Ive been trying many ways to do it but I dont have the best way now.
UUID is good but if use UUID, it face with many errors about DATE CREATED.
I find a package: https://github.com/JBKahn/django-sharding. Maybe It will help if anyone to try sharding database in Django.
Thank you! Tell me if you have a better solution!

**Comment by sebastian-code** [comment]
As I said before, perhaps I haven't been able to understand what you want, and perhaps that's the reason I still think _sharding_ will not solve your need. Beyond my previous suggestion of implementing UUID fields for every single model, I am out of ideas, but I wish you good look with that, yours truly sounds like a really interesting use case.

**Comment by feedgit** [comment]
Thank you @sebastian-code Hope your project will develop in the future. :)
