### ISSUE TITLE
Use ContentType for Activities

### ISSUE THREAD

**Issue by feedgit** [vitorfs/bootcamp#129]
Why dont you use ContentType for model Activities instead of having many fields? It makes more slot in database. Check this one: https://github.com/vitorfs/bootcamp/blob/master/bootcamp/activities/models.py.

How if I change to ContentType?

**Comment by sebastian-code** [comment]
Hi @feedgit 
You're most than welcome with any improvement on the code base, if you want to take a look, we discussed that topic a little bit in #118 with @ralphite and @vitorfs, talking about how to implement it, mainly because the migrations of this would make things harder to improve for the project user base.

**Comment by feedgit** [comment]
I implemented success in my project but If you guys have better solution. We can discus it in the future. Thank you very much!!
