### ISSUE TITLE
Hi, Please Share any tutorial or doc about "how to Run this on local server with sqlite3 db?"

### ISSUE THREAD

**Issue by soorajpazeekal** [vitorfs/bootcamp#182]

**Comment by sebastian-code** [comment]
Hi @soorajpazeekal This is out of the scope of the project and is not recommended. 

If you wish to do it that way, you have change the `.env` defaults, comment or delete the PostgreSQL constants and uncomment the `DATABASE_URL` one. Don't forget to edit the URL because that one is a non-working example.
