### ISSUE TITLE
ALLOWED_HOST variable should be optional

### ISSUE THREAD

**Issue by JeeveshN** [vitorfs/bootcamp#79]
I think the ALLOWED_HOST variable should be optional and should be in a try and except.

**Comment by sebastian-code** [comment]
Hi @JeeveshN it's an interesting idea, but why would you want to do that? Do you mind to walk us through your thinking process about your idea?

**Comment by JeeveshN** [comment]
@sebastian-code In my case it worked only after I put it inside a try and except.
Found the problem my default ALLOWED_HOST was not set that's why i was getting this error.In those cases in development environment i guess a try and catch would help.

**Comment by sebastian-code** [comment]
As I suggested in #78 Your issue in your development environment is than you did not declare the `ALLOWED_HOSTS` variable inside your .env file, and adding a try statement without a proper solution would hide/hinder your project execution and obviously adds unnecessary code.

That's why we didn't added in the first that kind of things to the code.
