### ISSUE TITLE
Reverse for 'profile' with arguments not found.

### ISSUE THREAD

**Issue by khizirsiddiqui** [vitorfs/bootcamp#83]
I am a beginner and I have copied the messenger to my site and changed the things required like bootcamp.messenger to messenger and other things as per my project.
I can open /new but when I open messages for individual user or the base page it shows this error:
`Reverse for 'profile' with arguments '('abc',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []`

I am using Django 1.10 Python 3.5

**Comment by sebastian-code** [comment]
Hi @KatherineMichel the main issue with your request is than this project is not designed to be easily broken, and obviously is out of the scope of this project.

The only thing I can say reading the message you're sharing is than your URL is returning empty, because the workflow is not properly implemented, it's calling the user app from this project.
