### ISSUE TITLE
How to introduce other post types

### ISSUE THREAD

**Issue by richardsonsamuel** [vitorfs/bootcamp#87]
Hi @vitorfs or @sebastian-code 

Just wondering what the best way to implement other post types such as attaching image or video, or sharing links (like how its done in Facebook),etc.

Even if you guys don't want to implement it, I'm doing the coding for my own forked project and was wondering the best way to go about this.

Thanks in advance.

**Comment by sebastian-code** [comment]
Hi @richardsonsamuel, to be honest, I haven't tried something like that, the feature you're looking for was out of the original scope; that functionality is actually useful in just a few scenarios, but is pretty doable.

What I would suggest is than you require to tweak a little bit the model to allow the new content you want to add, but you have to modify a lot the UI, because there is where the main changes are going to be needed, I guess you'll need new templates for every post type, also would be helpful to modify the Form.

I don't know if that is what you were looking for, of if in any case I was helpful, I hope I did.

In any case, if you find it suitable, you always can suggest a new PR to include those changes in the project, just don't forget to include some tests.

**Comment by richardsonsamuel** [comment]
Thanks this helps quite a bit. Closing the issue as all I needed was a bit of direction. Thanks again!
