### ISSUE TITLE
monthly_activity method has the same issue as daily_activities

### ISSUE THREAD

**Issue by SeekAndPwn** [vitorfs/bootcamp#98]
hey

you may want to  merge my patch or yours to the other function monthly_activity

My fix was:

```python

        query = Activity.objects.filter(user=user)
        if query.count() == 0:
            return json.dumps(None), json.dumps(None)
        query.annotate(month=TruncMonth('date')).values('month').annotate(
                       c=Count('id')).values('month', 'c')

        dates, datapoints = zip(
            *[[a['c'], str(a['month'].date())] for a in query])
        return json.dumps(dates), json.dumps(datapoints)

```

thanks

**Comment by sebastian-code** [comment]
Thanks @SeekAndPwn I notice it at the same time I fixed the previous (and related issue). I left it like that by the moment, because have not implement it yet, I was more trying to decide how to do it, but you're right, I should fix it.

I remember you actually asked about why to choose an `if` block over a `try` block. For me is about method and personal style, not forgetting that Python encourages the use of exceptions as expressed [here](https://docs.python.org/3/glossary.html#term-eafp) and `try` blocks are preferred over the `if/else` statements.
